# Generated by Django 5.0 on 2023-12-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
